/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as StartRouteImport } from './routes/start'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNekoAiRouteImport } from './routes/api/neko-ai'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNekoAiRouteImport } from './routes/_authenticated/neko-ai'
import { Route as AuthenticatedMissoesRouteImport } from './routes/_authenticated/missoes'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedAlfabetoRouteImport } from './routes/_authenticated/alfabeto'
import { Route as AuthenticatedAlfabetoIndexRouteImport } from './routes/_authenticated/alfabeto.index'
import { Route as AuthenticatedLessonIdRouteImport } from './routes/_authenticated/lesson.$id'
import { Route as AuthenticatedAlfabetoSystemRouteImport } from './routes/_authenticated/alfabeto.$system'
import { Route as AuthenticatedAlfabetoPtSectionRouteImport } from './routes/_authenticated/alfabeto-pt.$section'
import { Route as AuthenticatedAlfabetoEnSectionRouteImport } from './routes/_authenticated/alfabeto-en.$section'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNekoAiRoute = ApiNekoAiRouteImport.update({
  id: '/api/neko-ai',
  path: '/api/neko-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNekoAiRoute = AuthenticatedNekoAiRouteImport.update({
  id: '/neko-ai',
  path: '/neko-ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissoesRoute = AuthenticatedMissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlfabetoRoute = AuthenticatedAlfabetoRouteImport.update({
  id: '/alfabeto',
  path: '/alfabeto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlfabetoIndexRoute =
  AuthenticatedAlfabetoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAlfabetoRoute,
  } as any)
const AuthenticatedLessonIdRoute = AuthenticatedLessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlfabetoSystemRoute =
  AuthenticatedAlfabetoSystemRouteImport.update({
    id: '/$system',
    path: '/$system',
    getParentRoute: () => AuthenticatedAlfabetoRoute,
  } as any)
const AuthenticatedAlfabetoPtSectionRoute =
  AuthenticatedAlfabetoPtSectionRouteImport.update({
    id: '/alfabeto-pt/$section',
    path: '/alfabeto-pt/$section',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlfabetoEnSectionRoute =
  AuthenticatedAlfabetoEnSectionRouteImport.update({
    id: '/alfabeto-en/$section',
    path: '/alfabeto-en/$section',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start': typeof StartRoute
  '/welcome': typeof WelcomeRoute
  '/alfabeto': typeof AuthenticatedAlfabetoRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/missoes': typeof AuthenticatedMissoesRoute
  '/neko-ai': typeof AuthenticatedNekoAiRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/api/neko-ai': typeof ApiNekoAiRoute
  '/alfabeto-en/$section': typeof AuthenticatedAlfabetoEnSectionRoute
  '/alfabeto-pt/$section': typeof AuthenticatedAlfabetoPtSectionRoute
  '/alfabeto/$system': typeof AuthenticatedAlfabetoSystemRoute
  '/lesson/$id': typeof AuthenticatedLessonIdRoute
  '/alfabeto/': typeof AuthenticatedAlfabetoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start': typeof StartRoute
  '/welcome': typeof WelcomeRoute
  '/home': typeof AuthenticatedHomeRoute
  '/missoes': typeof AuthenticatedMissoesRoute
  '/neko-ai': typeof AuthenticatedNekoAiRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/store': typeof AuthenticatedStoreRoute
  '/api/neko-ai': typeof ApiNekoAiRoute
  '/alfabeto-en/$section': typeof AuthenticatedAlfabetoEnSectionRoute
  '/alfabeto-pt/$section': typeof AuthenticatedAlfabetoPtSectionRoute
  '/alfabeto/$system': typeof AuthenticatedAlfabetoSystemRoute
  '/lesson/$id': typeof AuthenticatedLessonIdRoute
  '/alfabeto': typeof AuthenticatedAlfabetoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start': typeof StartRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/alfabeto': typeof AuthenticatedAlfabetoRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/missoes': typeof AuthenticatedMissoesRoute
  '/_authenticated/neko-ai': typeof AuthenticatedNekoAiRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/api/neko-ai': typeof ApiNekoAiRoute
  '/_authenticated/alfabeto-en/$section': typeof AuthenticatedAlfabetoEnSectionRoute
  '/_authenticated/alfabeto-pt/$section': typeof AuthenticatedAlfabetoPtSectionRoute
  '/_authenticated/alfabeto/$system': typeof AuthenticatedAlfabetoSystemRoute
  '/_authenticated/lesson/$id': typeof AuthenticatedLessonIdRoute
  '/_authenticated/alfabeto/': typeof AuthenticatedAlfabetoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/start'
    | '/welcome'
    | '/alfabeto'
    | '/home'
    | '/missoes'
    | '/neko-ai'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/store'
    | '/api/neko-ai'
    | '/alfabeto-en/$section'
    | '/alfabeto-pt/$section'
    | '/alfabeto/$system'
    | '/lesson/$id'
    | '/alfabeto/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/start'
    | '/welcome'
    | '/home'
    | '/missoes'
    | '/neko-ai'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/store'
    | '/api/neko-ai'
    | '/alfabeto-en/$section'
    | '/alfabeto-pt/$section'
    | '/alfabeto/$system'
    | '/lesson/$id'
    | '/alfabeto'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/start'
    | '/welcome'
    | '/_authenticated/alfabeto'
    | '/_authenticated/home'
    | '/_authenticated/missoes'
    | '/_authenticated/neko-ai'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/store'
    | '/api/neko-ai'
    | '/_authenticated/alfabeto-en/$section'
    | '/_authenticated/alfabeto-pt/$section'
    | '/_authenticated/alfabeto/$system'
    | '/_authenticated/lesson/$id'
    | '/_authenticated/alfabeto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StartRoute: typeof StartRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiNekoAiRoute: typeof ApiNekoAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/neko-ai': {
      id: '/api/neko-ai'
      path: '/api/neko-ai'
      fullPath: '/api/neko-ai'
      preLoaderRoute: typeof ApiNekoAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/neko-ai': {
      id: '/_authenticated/neko-ai'
      path: '/neko-ai'
      fullPath: '/neko-ai'
      preLoaderRoute: typeof AuthenticatedNekoAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missoes': {
      id: '/_authenticated/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof AuthenticatedMissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alfabeto': {
      id: '/_authenticated/alfabeto'
      path: '/alfabeto'
      fullPath: '/alfabeto'
      preLoaderRoute: typeof AuthenticatedAlfabetoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alfabeto/': {
      id: '/_authenticated/alfabeto/'
      path: '/'
      fullPath: '/alfabeto/'
      preLoaderRoute: typeof AuthenticatedAlfabetoIndexRouteImport
      parentRoute: typeof AuthenticatedAlfabetoRoute
    }
    '/_authenticated/lesson/$id': {
      id: '/_authenticated/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof AuthenticatedLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alfabeto/$system': {
      id: '/_authenticated/alfabeto/$system'
      path: '/$system'
      fullPath: '/alfabeto/$system'
      preLoaderRoute: typeof AuthenticatedAlfabetoSystemRouteImport
      parentRoute: typeof AuthenticatedAlfabetoRoute
    }
    '/_authenticated/alfabeto-pt/$section': {
      id: '/_authenticated/alfabeto-pt/$section'
      path: '/alfabeto-pt/$section'
      fullPath: '/alfabeto-pt/$section'
      preLoaderRoute: typeof AuthenticatedAlfabetoPtSectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alfabeto-en/$section': {
      id: '/_authenticated/alfabeto-en/$section'
      path: '/alfabeto-en/$section'
      fullPath: '/alfabeto-en/$section'
      preLoaderRoute: typeof AuthenticatedAlfabetoEnSectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAlfabetoRouteChildren {
  AuthenticatedAlfabetoSystemRoute: typeof AuthenticatedAlfabetoSystemRoute
  AuthenticatedAlfabetoIndexRoute: typeof AuthenticatedAlfabetoIndexRoute
}

const AuthenticatedAlfabetoRouteChildren: AuthenticatedAlfabetoRouteChildren = {
  AuthenticatedAlfabetoSystemRoute: AuthenticatedAlfabetoSystemRoute,
  AuthenticatedAlfabetoIndexRoute: AuthenticatedAlfabetoIndexRoute,
}

const AuthenticatedAlfabetoRouteWithChildren =
  AuthenticatedAlfabetoRoute._addFileChildren(
    AuthenticatedAlfabetoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlfabetoRoute: typeof AuthenticatedAlfabetoRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMissoesRoute: typeof AuthenticatedMissoesRoute
  AuthenticatedNekoAiRoute: typeof AuthenticatedNekoAiRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedAlfabetoEnSectionRoute: typeof AuthenticatedAlfabetoEnSectionRoute
  AuthenticatedAlfabetoPtSectionRoute: typeof AuthenticatedAlfabetoPtSectionRoute
  AuthenticatedLessonIdRoute: typeof AuthenticatedLessonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlfabetoRoute: AuthenticatedAlfabetoRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMissoesRoute: AuthenticatedMissoesRoute,
  AuthenticatedNekoAiRoute: AuthenticatedNekoAiRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedAlfabetoEnSectionRoute: AuthenticatedAlfabetoEnSectionRoute,
  AuthenticatedAlfabetoPtSectionRoute: AuthenticatedAlfabetoPtSectionRoute,
  AuthenticatedLessonIdRoute: AuthenticatedLessonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StartRoute: StartRoute,
  WelcomeRoute: WelcomeRoute,
  ApiNekoAiRoute: ApiNekoAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
